
SELECT * FROM customer_shopping_behavior LIMIT 10;

SELECT * 
FROM customer_shopping_behavior
LIMIT 0;

`SELECT attname AS column_name
FROM pg_attribute
WHERE attrelid = 'customer_shopping_behavior'::regclass
AND attnum > 0
AND NOT attisdropped
ORDER BY attnum;`

-- Find the total number of customers in each age_group.

select age_group , count(customer_id) as Total_customer
from customer_shopping_behavior
group by age_group;
-- Find the total number of customers in each age_group.
select count(customer_id) from customer_shopping_behavior;
-- Calculate the average purchase amount for each category.
select category,avg("purchase_amount_(usd)") as average_purchage_amount
from customer_shopping_behavior
group by category;

-- Identify the top 5 most purchased items.

select item_purchased,count(*) as Total_purchased
from customer_shopping_behavior
group by item_purchased
order by Total_purchased asc
limit 5;

-- Find the total revenue generated by each season.
select season ,count("purchase_amount_(usd)") as total_Revenue_By_season
from customer_shopping_behavior
group by season;

-- Compare average spending of subscribers vs non-subscribers.
select subscription_status , count(subscription_status) as total_by_subscription_status
from customer_shopping_behavior
group by subscription_status
order by total_by_subscription_status;
-- List customers who made more than 5 previous purchases.
select customer_id,avg("purchase_amount_(usd)") as avg_purchase
from customer_shopping_behavior
group by customer_id
having avg("purchase_amount_(usd)")>(select avg("purchase_amount_(usd)") 
from customer_shopping_behavior)
order by avg_purchase desc
limit 10;

-- Determine which payment method is used most frequently.
select payment_method,count("purchase_amount_(usd)") as payment_method_by_method
from customer_shopping_behavior
group by payment_method
order by payment_method_by_method
limit 10;

-- Find the location with the highest total sales.
select location,sum("purchase_amount_(usd)") as location_total_sales
from customer_shopping_behavior
group by location
order by location_total_sales
limit 10;

-- Calculate the average review rating for each category.
select category,sum("purchase_amount_(usd)") as category_total_sales
from customer_shopping_behavior
group by category
order by category_total_sales
limit 10;
-- Identify customers who spend above the overall average purchase amount.
select payment_method,avg("purchase_amount_(usd)") AS total_sales
from customer_shopping_behavior
group by payment_method
having avg("purchase_amount_(usd)")>(select avg("purchase_amount_(usd)")
from customer_shopping_behavior);
-- Find how many times each promo code was used.
select promo_code_used,count(*) as promo_code_useds
from customer_shopping_behavior
group by promo_code_used
order by promo_code_useds
limit 10;
-- Analyze purchase frequency (frequency_purchases_days) to find highly active customers.
WITH median_freq AS (
    SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY frequency_purchases_days) AS median_days
    FROM customer_shopping_behavior
)
SELECT DISTINCT customer_id
FROM customer_shopping_behavior, median_freq
WHERE frequency_purchases_days < median_freq.median_days;
-- Find the most popular product size purchased by customers.
select size,count(*) as popular_product_size
from customer_shopping_behavior
group by size
order by popular_product_size desc;

-- Calculate total number of orders per shipping type.

select shipping_type,count(*) as popular_pshipping_type
from customer_shopping_behavior
group by shipping_type
order by popular_pshipping_type desc;
